# Generated by Django 5.2.17 on 2026-08-19 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=150)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em manutenção'), ('indisponivel', 'Indisponível')], default='ativo', max_length=20)),
            ],
            options={
                'verbose_name': 'Drone',
                'verbose_name_plural': 'Drones',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(blank=True, max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Piloto',
                'verbose_name_plural': 'Pilotos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('finalidade', models.CharField(choices=[('levantamento', 'Levantamento'), ('monitoramento', 'Monitoramento'), ('inspecao', 'Inspeção'), ('mapeamento', 'Mapeamento'), ('treinamento', 'Treinamento'), ('outro', 'Outro')], max_length=30)),
                ('local', models.CharField(max_length=200)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('bateria_inicial', models.PositiveIntegerField(blank=True, null=True)),
                ('bateria_final', models.PositiveIntegerField(blank=True, null=True)),
                ('distancia_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.drone')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.piloto')),
            ],
            options={
                'verbose_name': 'Voo',
                'verbose_name_plural': 'Voos',
                'ordering': ['-data', '-hora_inicio'],
            },
        ),
    ]
