# Generated by Django 5.2.17 on 2026-08-19 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drone',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='piloto',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='voo',
            options={'ordering': ['-data', '-hora_inicio']},
        ),
        migrations.AddField(
            model_name='piloto',
            name='perfil',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('usuario', 'Usuário')], default='usuario', max_length=20),
        ),
        migrations.AddField(
            model_name='piloto',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piloto', to=settings.AUTH_USER_MODEL),
        ),
    ]
