# Generated by Django 5.2.17 on 2026-08-19 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_drone_options_alter_piloto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('finalidade', models.CharField(max_length=100)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('reservado', 'Reservado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='reservado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.drone')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.piloto')),
            ],
            options={
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('inspecao', 'Inspeção'), ('atualizacao', 'Atualização')], max_length=30)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('concluida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.drone')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
    ]
