# Generated by Django 5.2.17 on 2026-08-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dronehistorico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alocacao',
            options={'ordering': ['data', 'hora_inicio'], 'verbose_name': 'Alocação', 'verbose_name_plural': 'Alocações'},
        ),
        migrations.AlterModelOptions(
            name='drone',
            options={'ordering': ['nome'], 'verbose_name': 'Drone', 'verbose_name_plural': 'Drones'},
        ),
        migrations.AlterModelOptions(
            name='dronehistorico',
            options={'ordering': ['-alterado_em'], 'verbose_name': 'Histórico do Drone', 'verbose_name_plural': 'Históricos dos Drones'},
        ),
        migrations.AlterModelOptions(
            name='manutencao',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Manutenção', 'verbose_name_plural': 'Manutenções'},
        ),
        migrations.AlterModelOptions(
            name='piloto',
            options={'ordering': ['nome'], 'verbose_name': 'Piloto', 'verbose_name_plural': 'Pilotos'},
        ),
        migrations.AlterModelOptions(
            name='voo',
            options={'ordering': ['-data', '-hora_inicio'], 'verbose_name': 'Voo', 'verbose_name_plural': 'Voos'},
        ),
    ]
