# Generated by Django 5.2.17 on 2026-08-20 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_drone_status_em_campo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoVoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('finalidade', models.CharField(max_length=100)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='solicitado', max_length=20)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('alocacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_voo', to='core.alocacao')),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_voo_analisadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_voo_criadas', to=settings.AUTH_USER_MODEL)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_voo', to='core.drone')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_voo', to='core.piloto')),
            ],
            options={
                'ordering': ['-data', '-hora_inicio', '-criado_em'],
            },
        ),
    ]
