# Generated by Django 5.2.17 on 2026-08-20 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_solicitacaovoo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistPreVoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bateria_ok', models.BooleanField(default=False)),
                ('helices_ok', models.BooleanField(default=False)),
                ('estrutura_ok', models.BooleanField(default=False)),
                ('controle_ok', models.BooleanField(default=False)),
                ('gps_ok', models.BooleanField(default=False)),
                ('memoria_ok', models.BooleanField(default=False)),
                ('area_segura', models.BooleanField(default=False)),
                ('meteorologia_ok', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('concluido', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('alocacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_pre_voo', to='core.alocacao')),
                ('preenchido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklists_pre_voo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
