# Generated by Django 5.2.17 on 2026-08-21 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_checklistprevoo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPosVoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio_real', models.TimeField()),
                ('hora_fim_real', models.TimeField()),
                ('resultado', models.CharField(choices=[('concluido', 'Concluído'), ('parcial', 'Parcial'), ('abortado', 'Abortado')], max_length=20)),
                ('baterias_utilizadas', models.PositiveIntegerField(default=1)),
                ('bateria_inicial', models.PositiveIntegerField(blank=True, null=True)),
                ('bateria_final', models.PositiveIntegerField(blank=True, null=True)),
                ('distancia_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ocorrencias', models.TextField(blank=True)),
                ('danos', models.TextField(blank=True)),
                ('necessita_manutencao', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('concluido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('alocacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_pos_voo', to='core.alocacao')),
                ('preenchido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_pos_voo', to=settings.AUTH_USER_MODEL)),
                ('voo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_pos_voo', to='core.voo')),
            ],
            options={
                'verbose_name': 'Registro pós-voo',
                'verbose_name_plural': 'Registros pós-voo',
                'ordering': ['-alocacao__data', '-hora_inicio_real'],
            },
        ),
    ]
