# Generated by Django 5.2.17 on 2026-08-24 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_registroposvoo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('capacidade_mah', models.PositiveIntegerField(blank=True, null=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('ciclos_informados', models.PositiveIntegerField(default=0)),
                ('saude_percentual', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em uso'), ('manutencao', 'Em manutenção'), ('descartada', 'Descartada')], default='disponivel', max_length=20)),
                ('localizacao', models.CharField(blank=True, max_length=150)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baterias', to='core.drone')),
            ],
            options={
                'verbose_name': 'Bateria',
                'verbose_name_plural': 'Baterias',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='registroposvoo',
            name='baterias',
            field=models.ManyToManyField(blank=True, related_name='registros_pos_voo', to='core.bateria'),
        ),
    ]
