# Generated by Django 5.2.17 on 2026-08-24 09:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bateria_registroposvoo_baterias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoInspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('inspecao', 'Inspeção'), ('preventiva', 'Manutenção preventiva'), ('componente', 'Substituição de componente'), ('bateria', 'Verificação de bateria')], default='inspecao', max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('intervalo_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('intervalo_voos', models.PositiveIntegerField(blank=True, null=True)),
                ('intervalo_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('intervalo_ciclos', models.PositiveIntegerField(blank=True, null=True)),
                ('ultima_execucao', models.DateField(default=datetime.date.today)),
                ('voos_base', models.PositiveIntegerField(default=0)),
                ('minutos_base', models.PositiveIntegerField(default=0)),
                ('ciclos_base', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('bateria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_inspecao', to='core.bateria')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_inspecao_criados', to=settings.AUTH_USER_MODEL)),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_inspecao', to='core.drone')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoInspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('executado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='core.planoinspecao')),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
