# Generated by Django 5.2.17 on 2026-08-24 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_planoinspecao_execucaoinspecao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('habilitacao', 'Habilitação / certificado de piloto'), ('registro_drone', 'Registro do drone'), ('seguro', 'Seguro'), ('autorizacao', 'Autorização'), ('treinamento', 'Treinamento'), ('manual', 'Manual'), ('nota_fiscal', 'Nota fiscal'), ('outro', 'Outro')], max_length=30)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('organizacional', models.BooleanField(default=False)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos/%Y/%m/')),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('bateria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.bateria')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_criados', to=settings.AUTH_USER_MODEL)),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.drone')),
                ('piloto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.piloto')),
            ],
            options={
                'ordering': ['data_validade', 'titulo'],
            },
        ),
    ]
