# Generated by Django 5.2.17 on 2026-08-24 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perigos_identificados', models.TextField()),
                ('probabilidade_inicial', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito baixo'), (2, '2 - Baixo'), (3, '3 - Moderado'), (4, '4 - Alto'), (5, '5 - Muito alto')])),
                ('impacto_inicial', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito baixo'), (2, '2 - Baixo'), (3, '3 - Moderado'), (4, '4 - Alto'), (5, '5 - Muito alto')])),
                ('medidas_mitigadoras', models.TextField()),
                ('probabilidade_residual', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito baixo'), (2, '2 - Baixo'), (3, '3 - Moderado'), (4, '4 - Alto'), (5, '5 - Muito alto')])),
                ('impacto_residual', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito baixo'), (2, '2 - Baixo'), (3, '3 - Moderado'), (4, '4 - Alto'), (5, '5 - Muito alto')])),
                ('condicoes_meteorologicas', models.TextField(blank=True)),
                ('pessoas_expostas', models.BooleanField(default=False)),
                ('area_controlada', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('submetida', 'Aguardando análise'), ('aprovada', 'Aprovada'), ('revisao', 'Requer revisão')], default='rascunho', max_length=20)),
                ('analisado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_risco_analisadas', to=settings.AUTH_USER_MODEL)),
                ('preenchido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_risco_preenchidas', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_risco', to='core.solicitacaovoo')),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('falha_equipamento', 'Falha de equipamento'), ('perda_sinal', 'Perda de sinal'), ('queda', 'Queda / colisão'), ('violacao_espaco', 'Violação de espaço aéreo'), ('lesao', 'Lesão a pessoa'), ('dano_terceiro', 'Dano a terceiro'), ('quase_acidente', 'Quase acidente'), ('outro', 'Outro')], max_length=30)),
                ('gravidade', models.CharField(choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('grave', 'Grave'), ('critico', 'Crítico')], max_length=20)),
                ('data_hora', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('acoes_imediatas', models.TextField(blank=True)),
                ('danos', models.TextField(blank=True)),
                ('houve_lesao', models.BooleanField(default=False)),
                ('houve_dano_terceiro', models.BooleanField(default=False)),
                ('notificacao_obrigatoria', models.BooleanField(default=False)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='incidentes/%Y/%m/')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('investigacao', 'Em investigação'), ('encerrado', 'Encerrado')], default='aberto', max_length=20)),
                ('causa_raiz', models.TextField(blank=True)),
                ('acoes_corretivas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('alocacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='core.alocacao')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_registrados', to=settings.AUTH_USER_MODEL)),
                ('responsavel_investigacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_investigados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
