# Generated by Django 5.2.17 on 2026-08-24 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_avaliacaorisco_incidente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificacaoPiloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('categoria', models.CharField(choices=[('regulatoria', 'Regulatória'), ('modelo_drone', 'Modelo de drone'), ('tipo_operacao', 'Tipo de operação'), ('seguranca', 'Segurança'), ('software', 'Software / processamento'), ('instrutor', 'Instrutor'), ('outro', 'Outro')], max_length=30)),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('instrutor', 'Instrutor')], default='basico', max_length=20)),
                ('instituicao', models.CharField(blank=True, max_length=150)),
                ('numero_certificado', models.CharField(blank=True, max_length=100)),
                ('modelo_drone', models.CharField(blank=True, max_length=150)),
                ('tipo_operacao', models.CharField(blank=True, max_length=150)),
                ('carga_horaria', models.PositiveIntegerField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualificacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualificacoes', to='core.documento')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualificacoes', to='core.piloto')),
            ],
            options={
                'ordering': ['piloto__nome', 'categoria', 'nome'],
            },
        ),
    ]
