# Generated by Django 5.2.17 on 2026-08-25 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_qualificacaopiloto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='telemetria/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('formato', models.CharField(default='csv', max_length=20)),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='processando', max_length=20)),
                ('total_pontos', models.PositiveIntegerField(default=0)),
                ('duracao_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('altitude_maxima_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('velocidade_maxima_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distancia_calculada_m', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bateria_inicial', models.PositiveIntegerField(blank=True, null=True)),
                ('bateria_final', models.PositiveIntegerField(blank=True, null=True)),
                ('total_alertas', models.PositiveIntegerField(default=0)),
                ('colunas_reconhecidas', models.JSONField(blank=True, default=list)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('importado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_importados', to=settings.AUTH_USER_MODEL)),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importacoes_log', to='core.voo')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PontoTelemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField()),
                ('instante', models.DateTimeField(blank=True, null=True)),
                ('segundos', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('altitude_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('velocidade_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bateria_percentual', models.PositiveIntegerField(blank=True, null=True)),
                ('satelites', models.PositiveIntegerField(blank=True, null=True)),
                ('sinal_percentual', models.PositiveIntegerField(blank=True, null=True)),
                ('alerta', models.CharField(blank=True, max_length=255)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='core.importacaolog')),
            ],
            options={
                'ordering': ['indice'],
                'constraints': [models.UniqueConstraint(fields=('importacao', 'indice'), name='telemetria_indice_unico')],
            },
        ),
    ]
