# Generated by Django 5.2.17 on 2026-08-25 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_importacaolog_pontotelemetria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('camera', 'Câmera'), ('sensor', 'Sensor'), ('helice', 'Hélice'), ('motor', 'Motor'), ('gimbal', 'Gimbal'), ('controle', 'Controle'), ('carregador', 'Carregador'), ('acessorio', 'Acessório'), ('outro', 'Outro')], max_length=30)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('instalado', 'Instalado'), ('manutencao', 'Em manutenção'), ('indisponivel', 'Indisponível'), ('baixado', 'Baixado')], default='disponivel', max_length=20)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('data_instalacao', models.DateField(blank=True, null=True)),
                ('vida_util_horas', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='core.drone')),
            ],
            options={
                'ordering': ['tipo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='core.componente')),
                ('drone_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentes_removidos', to='core.drone')),
                ('drone_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentes_instalados', to='core.drone')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
