# Generated by Django 5.2.17 on 2026-08-25 07:18

import django.db.models.deletion
from django.db import migrations, models


def vincular_alocacoes_existentes(apps, schema_editor):
    Voo = apps.get_model('core', 'Voo')
    Alocacao = apps.get_model('core', 'Alocacao')
    usados = set()
    for voo in Voo.objects.order_by('pk'):
        alocacao = Alocacao.objects.filter(
            piloto_id=voo.piloto_id, drone_id=voo.drone_id, data=voo.data,
            hora_inicio=voo.hora_inicio, hora_fim=voo.hora_fim,
        ).exclude(pk__in=usados).first()
        if alocacao:
            voo.alocacao_calendario_id = alocacao.pk
            voo.save(update_fields=['alocacao_calendario'])
            usados.add(alocacao.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_componente_movimentacaocomponente'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='prefixo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Prefixo'),
        ),
        migrations.AddField(
            model_name='piloto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='voo',
            name='alocacao_calendario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voo_sincronizado', to='core.alocacao'),
        ),
        migrations.RunPython(vincular_alocacoes_existentes, migrations.RunPython.noop),
    ]
