# Generated by Django 5.2.17 on 2026-08-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_drone_prefixo_piloto_foto_voo_alocacao_calendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaolog',
            name='bateria_serial_detectada',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='importacaolog',
            name='drone_modelo_detectado',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='importacaolog',
            name='drone_serial_detectado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='importacaolog',
            name='origem',
            field=models.CharField(default='csv', max_length=30),
        ),
        migrations.AddField(
            model_name='importacaolog',
            name='versao_log',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
