# Generated by Django 5.2.17 on 2026-08-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ajustar_duracao_dji_acumulada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voo',
            name='finalidade',
            field=models.CharField(choices=[('levantamento', 'Levantamento'), ('monitoramento', 'Monitoramento'), ('inspecao', 'Inspeção'), ('mapeamento', 'Mapeamento'), ('fotografia', 'Fotografia'), ('treinamento', 'Treinamento'), ('outro', 'Outro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='voo',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voo',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
