# Generated by Django 5.2.17 on 2026-08-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_corrigir_duracao_dji_por_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaolog',
            name='fim_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importacaolog',
            name='inicio_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
