# Generated by Django 5.2.17 on 2026-08-25 09:33

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def consolidar_voos_duplicados(apps, schema_editor):
    Voo = apps.get_model("core", "Voo")
    ImportacaoLog = apps.get_model("core", "ImportacaoLog")
    RegistroPosVoo = apps.get_model("core", "RegistroPosVoo")
    SolicitacaoVoo = apps.get_model("core", "SolicitacaoVoo")
    ChecklistPreVoo = apps.get_model("core", "ChecklistPreVoo")
    Alocacao = apps.get_model("core", "Alocacao")

    grupos = Voo.objects.exclude(data__isnull=True).values(
        "data", "piloto_id", "drone_id"
    ).annotate(total=Count("id")).filter(total__gt=1)

    for grupo in grupos.iterator():
        voos = list(Voo.objects.filter(
            data=grupo["data"], piloto_id=grupo["piloto_id"], drone_id=grupo["drone_id"],
        ).order_by("pk"))
        canonical = max(voos, key=lambda voo: (ImportacaoLog.objects.filter(voo_id=voo.pk).count(), -voo.pk))
        ordenados = sorted(voos, key=lambda voo: (voo.hora_inicio is None, voo.hora_inicio))
        inicios = [voo.hora_inicio for voo in voos if voo.hora_inicio]
        finais = [voo.hora_fim for voo in voos if voo.hora_fim]
        distancias = [voo.distancia_m for voo in voos if voo.distancia_m is not None]
        canonical.hora_inicio = min(inicios) if inicios else None
        canonical.hora_fim = max(finais) if finais else None
        canonical.distancia_m = sum(distancias) if distancias else None
        baterias_iniciais = [voo.bateria_inicial for voo in ordenados if voo.bateria_inicial is not None]
        baterias_finais = [voo.bateria_final for voo in ordenados if voo.bateria_final is not None]
        canonical.bateria_inicial = baterias_iniciais[0] if baterias_iniciais else None
        canonical.bateria_final = baterias_finais[-1] if baterias_finais else None
        canonical.save(update_fields=["hora_inicio", "hora_fim", "distancia_m", "bateria_inicial", "bateria_final"])

        for duplicado in voos:
            if duplicado.pk == canonical.pk:
                continue
            ImportacaoLog.objects.filter(voo_id=duplicado.pk).update(voo_id=canonical.pk)
            registros = RegistroPosVoo.objects.filter(voo_id=duplicado.pk)
            if registros.exists() and not RegistroPosVoo.objects.filter(voo_id=canonical.pk).exists():
                registros.update(voo_id=canonical.pk)
            else:
                registros.update(voo_id=None)
            alocacao_id = duplicado.alocacao_calendario_id
            duplicado.delete()
            if alocacao_id and not (
                SolicitacaoVoo.objects.filter(alocacao_id=alocacao_id).exists()
                or ChecklistPreVoo.objects.filter(alocacao_id=alocacao_id).exists()
                or RegistroPosVoo.objects.filter(alocacao_id=alocacao_id).exists()
            ):
                Alocacao.objects.filter(pk=alocacao_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_importacaolog_fim_registro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(consolidar_voos_duplicados, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='voo',
            constraint=models.UniqueConstraint(condition=models.Q(('data__isnull', False)), fields=('data', 'piloto', 'drone'), name='voo_unico_por_data_piloto_drone'),
        ),
    ]
