# Generated by Django 5.2.17 on 2026-08-25 10:12

from django.db import migrations, models


def atualizar_solicitacoes_existentes(apps, schema_editor):
    SolicitacaoVoo = apps.get_model('core', 'SolicitacaoVoo')
    Alocacao = apps.get_model('core', 'Alocacao')
    Voo = apps.get_model('core', 'Voo')

    SolicitacaoVoo.objects.filter(avaliacao_risco__isnull=False).update(
        requer_avaliacao_risco=True
    )
    pendentes = SolicitacaoVoo.objects.filter(
        status='solicitado',
        avaliacao_risco__status='aprovada',
    ).select_related('avaliacao_risco')
    finalidades = {
        'levantamento', 'monitoramento', 'inspecao', 'mapeamento',
        'fotografia', 'treinamento', 'outro',
    }
    for solicitacao in pendentes:
        conflito = Alocacao.objects.filter(
            data=solicitacao.data,
            drone_id=solicitacao.drone_id,
            status='reservado',
            hora_inicio__lt=solicitacao.hora_fim,
            hora_fim__gt=solicitacao.hora_inicio,
        ).exists()
        if conflito:
            continue
        usuario_id = (
            solicitacao.avaliacao_risco.analisado_por_id
            or solicitacao.criado_por_id
        )
        alocacao = Alocacao.objects.create(
            data=solicitacao.data,
            hora_inicio=solicitacao.hora_inicio,
            hora_fim=solicitacao.hora_fim,
            piloto_id=solicitacao.piloto_id,
            drone_id=solicitacao.drone_id,
            finalidade=solicitacao.finalidade,
            local=solicitacao.local,
            observacoes=solicitacao.observacoes,
            status='reservado',
            criado_por_id=usuario_id,
        )
        finalidade = (solicitacao.finalidade or '').lower()
        if finalidade not in finalidades:
            finalidade = 'fotografia' if 'fotograf' in finalidade else 'outro'
        voo, _ = Voo.objects.get_or_create(
            data=solicitacao.data,
            piloto_id=solicitacao.piloto_id,
            drone_id=solicitacao.drone_id,
            defaults={
                'hora_inicio': solicitacao.hora_inicio,
                'hora_fim': solicitacao.hora_fim,
                'finalidade': finalidade,
                'local': solicitacao.local,
                'observacoes': solicitacao.observacoes,
                'criado_por_id': solicitacao.criado_por_id,
                'alocacao_calendario_id': alocacao.id,
            },
        )
        voo.alocacao_calendario_id = alocacao.id
        voo.save(update_fields=['alocacao_calendario'])
        solicitacao.status = 'aprovado'
        solicitacao.analisado_por_id = usuario_id
        solicitacao.alocacao_id = alocacao.id
        solicitacao.save(update_fields=['status', 'analisado_por', 'alocacao'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_voo_voo_unico_por_data_piloto_drone'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaovoo',
            name='requer_avaliacao_risco',
            field=models.BooleanField(default=False, verbose_name='Necessita avaliação de risco operacional'),
        ),
        migrations.RunPython(atualizar_solicitacoes_existentes, migrations.RunPython.noop),
    ]
