# Generated by Django 5.2.17 on 2026-08-25 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_recalcular_horarios_voos_telemetria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanejamentoVoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('altura_maxima_m', models.PositiveIntegerField(default=120)),
                ('area_geojson', models.JSONField()),
                ('centro_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('centro_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status_meteorologico', models.CharField(choices=[('nao_consultado', 'Não consultado'), ('favoravel', 'Favorável'), ('atencao', 'Atenção'), ('desfavoravel', 'Desfavorável'), ('indisponivel', 'Previsão indisponível')], default='nao_consultado', max_length=20)),
                ('resumo_meteorologico', models.JSONField(blank=True, default=dict)),
                ('previsao_consultada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planejamentos_voo_criados', to=settings.AUTH_USER_MODEL)),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planejamentos_voo', to='core.piloto')),
            ],
            options={
                'verbose_name': 'Planejamento de voo',
                'verbose_name_plural': 'Planejamentos de voo',
                'ordering': ['-data', '-hora_inicio'],
            },
        ),
        migrations.AddField(
            model_name='solicitacaovoo',
            name='planejamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_voo', to='core.planejamentovoo'),
        ),
    ]
