# Generated by Django 5.2.17 on 2026-08-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_planejamentovoo_solicitacaovoo_planejamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamentovoo',
            name='local',
            field=models.CharField(blank=True, max_length=200, verbose_name='Local/região'),
        ),
    ]
