# Generated by Django 5.2.17 on 2026-08-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_planejamentovoo_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaovoo',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Pendente de avaliação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='solicitado', max_length=20),
        ),
    ]
