# Generated by Django 5.2.17 on 2026-08-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_solicitacaovoo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaovoo',
            name='finalidade',
            field=models.CharField(choices=[('levantamento', 'Levantamento'), ('monitoramento', 'Monitoramento'), ('inspecao', 'Inspeção'), ('mapeamento', 'Mapeamento'), ('fotografia', 'Fotografia'), ('treinamento', 'Treinamento'), ('outro', 'Outro')], max_length=100),
        ),
    ]
