# Generated by Django 5.2.17 on 2026-08-26 01:57

from django.db import migrations, models


def normalizar_status(apps, schema_editor):
    AvaliacaoRisco = apps.get_model("core", "AvaliacaoRisco")
    AvaliacaoRisco.objects.filter(status__in=["submetida", "revisao"]).update(status="rascunho")
    for avaliacao in AvaliacaoRisco.objects.filter(status="aprovada", aceito_em__isnull=True):
        avaliacao.aceito_em = avaliacao.atualizado_em
        avaliacao.save(update_fields=["aceito_em"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_normalizar_finalidades_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaorisco',
            name='aceito_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaorisco',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aprovada', 'Aceita pelo piloto')], default='rascunho', max_length=20),
        ),
        migrations.RunPython(normalizar_status, migrations.RunPython.noop),
    ]
