# Generated by Django 5.2.17 on 2026-08-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_avaliacaorisco_aceito_em_alter_avaliacaorisco_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaovoo',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Pendente de avaliação'), ('aprovado', 'Reservado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='solicitado', max_length=20),
        ),
    ]
