# Generated by Django 5.2.17 on 2026-08-26 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_solicitacaovoo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaorisco',
            name='aeronave_identificacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avaliacaorisco',
            name='area_distante_terceiros',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_aplicavel', 'Não aplicável')], max_length=20),
        ),
        migrations.AddField(
            model_name='avaliacaorisco',
            name='aspectos_gerais',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avaliacaorisco',
            name='cenario_operacional',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avaliacaorisco',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='avaliacaorisco',
            name='declaracao_conformidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avaliacaorisco',
            name='descricao_treinamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avaliacaorisco',
            name='legislacao_aplicavel',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avaliacaorisco',
            name='matriz_risco',
            field=models.CharField(blank=True, default='Matriz 5 × 5 da IS E94-003A', max_length=150),
        ),
        migrations.AddField(
            model_name='avaliacaorisco',
            name='operador_documento',
            field=models.CharField(blank=True, max_length=30, verbose_name='CPF/CNPJ do operador'),
        ),
        migrations.AddField(
            model_name='avaliacaorisco',
            name='operador_nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='avaliacaorisco',
            name='procedimento_acidente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avaliacaorisco',
            name='responsavel_informacoes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='avaliacaorisco',
            name='situacoes_risco',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='avaliacaorisco',
            name='treinamento_requerido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avaliacaorisco',
            name='validade_ate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
