# Generated by Django 5.2.17 on 2026-08-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_avaliacaorisco_aeronave_identificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaorisco',
            name='codigo_sarpas',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código SARPAS'),
        ),
        migrations.AddField(
            model_name='piloto',
            name='codigo_sarpas',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código SARPAS'),
        ),
        migrations.AddField(
            model_name='piloto',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
    ]
