# Generated by Django 5.2.17 on 2026-08-26 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_avaliacaorisco_codigo_sarpas_piloto_codigo_sarpas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPapelTimbrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_relatorios', models.FileField(blank=True, null=True, upload_to='papel_timbrado/')),
                ('modelo_avaliacao_risco', models.FileField(blank=True, null=True, upload_to='papel_timbrado/')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de papel timbrado',
                'verbose_name_plural': 'Configurações de papel timbrado',
            },
        ),
    ]
