# Generated by Django 5.2.17 on 2026-08-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_configuracaopapeltimbrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamentovoo',
            name='atividade_agroflorestal',
            field=models.BooleanField(default=False, verbose_name='Atividade agroflorestal'),
        ),
        migrations.AddField(
            model_name='planejamentovoo',
            name='dentro_condicionantes_ica',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_sei', 'Não sei / confirmar')], default='nao_sei', max_length=12, verbose_name='Operação dentro das condicionantes da ICA 100-40'),
        ),
        migrations.AddField(
            model_name='planejamentovoo',
            name='exclusivo_proprietario_rural',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_sei', 'Não sei / confirmar')], default='nao_sei', max_length=12, verbose_name='Destinado exclusivamente ao proprietário do imóvel rural'),
        ),
        migrations.AddField(
            model_name='planejamentovoo',
            name='finalidade',
            field=models.CharField(choices=[('levantamento', 'Levantamento'), ('monitoramento', 'Monitoramento'), ('inspecao', 'Inspeção'), ('mapeamento', 'Mapeamento'), ('fotografia', 'Fotografia'), ('treinamento', 'Treinamento'), ('outro', 'Outro')], default='outro', max_length=100),
        ),
        migrations.AddField(
            model_name='planejamentovoo',
            name='gera_dados_aerolevantamento',
            field=models.BooleanField(default=False, help_text='Marque se haverá captura destinada a ortomosaico, mapa, modelo 3D, nuvem de pontos, LiDAR, dado espectral ou geofísico.', verbose_name='A operação produzirá dados de aerolevantamento'),
        ),
        migrations.AddField(
            model_name='planejamentovoo',
            name='interseca_area_sensivel_defesa',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_sei', 'Não sei / confirmar')], default='nao_sei', max_length=12, verbose_name='Interseção com área/instalação sensível à Defesa'),
        ),
        migrations.AddField(
            model_name='planejamentovoo',
            name='projeto_contiguo_12_meses',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_sei', 'Não sei / confirmar')], default='nao_sei', max_length=12, verbose_name='Projeto contíguo executado nos últimos 12 meses'),
        ),
        migrations.AddField(
            model_name='planejamentovoo',
            name='tipo_aerolevantamento',
            field=models.CharField(blank=True, choices=[('fotogrametrico', 'Aerofotogramétrico / ortomosaico / modelo 3D'), ('laser', 'Varredura a laser / LiDAR'), ('espectral', 'Pancromático ou espectral'), ('geofisico', 'Aerogeofísico'), ('outro', 'Outro aerolevantamento')], max_length=30),
        ),
    ]
