# Generated by Django 5.2.17 on 2026-08-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_planejamentovoo_atividade_agroflorestal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='perfil',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('coordenador', 'Coordenador'), ('usuario', 'Usuário')], default='usuario', max_length=20),
        ),
    ]
