# Generated by Django 5.2.17 on 2026-08-26 15:02

import django.db.models.deletion
from django.db import migrations, models


def preencher_datas_finais(apps, schema_editor):
    for nome_modelo in ("Alocacao", "SolicitacaoVoo"):
        modelo = apps.get_model("core", nome_modelo)
        for item in modelo.objects.filter(data_fim__isnull=True).iterator():
            item.data_fim = item.data
            item.save(update_fields=["data_fim"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_piloto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de finalização'),
        ),
        migrations.AddField(
            model_name='solicitacaovoo',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de finalização'),
        ),
        migrations.RunPython(preencher_datas_finais, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='solicitacaovoo',
            name='planejamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_voo', to='core.planejamentovoo'),
        ),
    ]
