# Generated by Django 5.2.17 on 2026-08-26 15:56

from django.db import migrations, models


def preencher_data_final(apps, schema_editor):
    PlanejamentoVoo = apps.get_model("core", "PlanejamentoVoo")
    for planejamento in PlanejamentoVoo.objects.filter(data_fim__isnull=True).iterator():
        planejamento.data_fim = planejamento.data
        planejamento.save(update_fields=["data_fim"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_periodo_reserva_multiplos_drones'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamentovoo',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data final'),
        ),
        migrations.RunPython(preencher_data_final, migrations.RunPython.noop),
    ]
