# Generated by Django 5.2.17 on 2026-08-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_planejamentovoo_data_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='bateria',
            name='ciclos_detectados_log',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='importacaolog',
            name='bateria_ciclos_detectados',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
