# Generated by Django 5.2.17 on 2026-08-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_bateria_ciclos_detectados_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaolog',
            name='componentes_detectados',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
