# Generated by Django 5.2.17 on 2026-08-28 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_importacaolog_componentes_detectados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaResolvido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('resolvido_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_resolvidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-resolvido_em'],
            },
        ),
    ]
