# Generated by Django 5.2.17 on 2026-08-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alertaresolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='localizacao',
            field=models.CharField(blank=True, max_length=180, verbose_name='Localização'),
        ),
    ]
