# Generated by Django 5.2.17 on 2026-08-28 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_componente_localizacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoCoordenacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_tipo', models.CharField(max_length=30)),
                ('referencia_id', models.CharField(max_length=80)),
                ('referencia_nome', models.CharField(blank=True, max_length=180)),
                ('operador_nome', models.CharField(max_length=180)),
                ('operador_endereco', models.CharField(blank=True, max_length=255)),
                ('operador_telefone', models.CharField(blank=True, max_length=50)),
                ('operador_email', models.EmailField(blank=True, max_length=254)),
                ('operador_sarpas', models.CharField(blank=True, max_length=80)),
                ('responsavel_nome', models.CharField(blank=True, max_length=180)),
                ('responsavel_funcao', models.CharField(blank=True, max_length=120)),
                ('responsavel_endereco', models.CharField(blank=True, max_length=255)),
                ('responsavel_telefone', models.CharField(blank=True, max_length=50)),
                ('responsavel_email', models.EmailField(blank=True, max_length=254)),
                ('local_codigo', models.CharField(blank=True, max_length=80)),
                ('local_natureza', models.CharField(blank=True, max_length=160)),
                ('local_funcionamento', models.CharField(blank=True, max_length=160)),
                ('local_observacoes', models.TextField(blank=True)),
                ('limites_verticais', models.CharField(blank=True, max_length=180)),
                ('limites_laterais', models.TextField(blank=True)),
                ('coordenadas_wgs84', models.TextField(blank=True)),
                ('objetivo_operacao', models.CharField(max_length=255)),
                ('periodo_operacao', models.CharField(max_length=120)),
                ('frequencia_duracao', models.CharField(blank=True, max_length=160)),
                ('horarios_operacao', models.CharField(max_length=120)),
                ('tipo_operacao', models.CharField(choices=[('VLOS', 'VLOS'), ('EVLOS', 'EVLOS'), ('BVLOS', 'BVLOS')], default='VLOS', max_length=10)),
                ('operacao_observacoes', models.TextField(blank=True)),
                ('contato_previo', models.BooleanField(null=True)),
                ('informar_inicio_termino', models.BooleanField(null=True)),
                ('pessoal_dedicado_contatos', models.BooleanField(null=True)),
                ('suspensao_por_seguranca', models.BooleanField(null=True)),
                ('informar_contingencia', models.BooleanField(null=True)),
                ('procedimentos_emergencia', models.BooleanField(null=True)),
                ('descricao_coordenacao', models.TextField(blank=True)),
                ('validade_meses', models.PositiveSmallIntegerField(default=1)),
                ('local_assinatura', models.CharField(blank=True, max_length=120)),
                ('data_assinatura', models.DateField(blank=True, null=True)),
                ('representante_operador', models.CharField(blank=True, max_length=180)),
                ('representante_ats', models.CharField(blank=True, max_length=180)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos_coordenacao_atualizados', to=settings.AUTH_USER_MODEL)),
                ('planejamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_coordenacao', to='core.planejamentovoo')),
            ],
            options={
                'ordering': ['referencia_tipo', 'referencia_id'],
                'constraints': [models.UniqueConstraint(fields=('planejamento', 'referencia_tipo', 'referencia_id'), name='termo_coordenacao_referencia_unica')],
            },
        ),
    ]
