# Generated by Django 5.2.17 on 2026-08-28 23:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_termocoordenacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissaoAoVivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('chave_stream', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('aeronave_serial', models.CharField(blank=True, max_length=100)),
                ('controle_serial', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('preparada', 'Preparada'), ('ao_vivo', 'Ao vivo'), ('finalizada', 'Finalizada'), ('erro', 'Erro')], default='preparada', max_length=20)),
                ('metricas', models.JSONField(blank=True, default=dict)),
                ('mensagem_erro', models.CharField(blank=True, max_length=255)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('alocacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmissoes_ao_vivo', to='core.alocacao')),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmissoes_ao_vivo', to='core.drone')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transmissoes_ao_vivo', to='core.piloto')),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
