# Generated by Django 5.2.17 on 2026-08-29 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_transmissaoaovivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamentovoo',
            name='livestream_acesso',
            field=models.CharField(choices=[('coordenacao', 'Coordenadores e administradores'), ('administracao', 'Somente administradores')], default='coordenacao', max_length=20, verbose_name='Quem poderá assistir'),
        ),
        migrations.AddField(
            model_name='planejamentovoo',
            name='livestream_gravar',
            field=models.BooleanField(default=False, verbose_name='Gravar a transmissão quando o servidor permitir'),
        ),
        migrations.AddField(
            model_name='planejamentovoo',
            name='livestream_planejada',
            field=models.BooleanField(default=False, verbose_name='Transmitir esta operação ao vivo'),
        ),
        migrations.AddField(
            model_name='planejamentovoo',
            name='livestream_titulo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Título da transmissão'),
        ),
        migrations.AddField(
            model_name='transmissaoaovivo',
            name='origem',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('avulsa', 'Avulsa')], default='avulsa', max_length=20),
        ),
        migrations.AddField(
            model_name='transmissaoaovivo',
            name='planejamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmissoes_ao_vivo', to='core.planejamentovoo'),
        ),
    ]
