# Generated by Django 5.2.17 on 2026-08-31 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_planejamentovoo_livestream_acesso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalacaoSISMOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instalação SISMOD',
                'verbose_name_plural': 'Instalações SISMOD',
            },
        ),
        migrations.CreateModel(
            name='LicencaSISMOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100, unique=True)),
                ('empresa_nome', models.CharField(max_length=200)),
                ('empresa_cnpj', models.CharField(blank=True, max_length=30)),
                ('emitida_em', models.DateField()),
                ('valida_ate', models.DateField()),
                ('tolerancia_dias', models.PositiveSmallIntegerField(default=15)),
                ('recursos', models.JSONField(blank=True, default=list)),
                ('conteudo', models.JSONField(default=dict)),
                ('assinatura', models.TextField()),
                ('ativa', models.BooleanField(default=True)),
                ('ativada_em', models.DateTimeField(auto_now_add=True)),
                ('ativada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('instalacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licencas', to='core.instalacaosismod')),
            ],
            options={
                'verbose_name': 'Licença SISMOD',
                'verbose_name_plural': 'Licenças SISMOD',
                'ordering': ['-ativada_em'],
            },
        ),
    ]
