# Generated by Django 5.2.17 on 2026-09-02 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_dji_dock_resultados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='djidockmissao',
            name='altura_retorno_m',
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='djidockmissao',
            name='armazenamento_minimo_mb',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='djidockmissao',
            name='bateria_minima_percent',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='djidockmissao',
            name='interromper_na_perda_sinal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='djidockmissao',
            name='parametros_confirmados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='djidockmissao',
            name='parametros_confirmados_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djidockmissao',
            name='parametros_confirmados_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missoes_dock_parametros_confirmados', to=settings.AUTH_USER_MODEL),
        ),
    ]
