# Generated by Django 5.2.17 on 2026-09-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_dji_dock_parametros_operacionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='djidockarquivo',
            name='armazenado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djidockarquivo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='dji-dock/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='djidockarquivo',
            name='backend',
            field=models.CharField(choices=[('local', 'Local'), ('s3', 'Amazon S3'), ('minio', 'MinIO')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='djidockarquivo',
            name='checksum',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='djidockarquivo',
            name='mensagem_erro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='djidockarquivo',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('recebendo', 'Recebendo'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='aguardando', max_length=20),
        ),
        migrations.AddField(
            model_name='djidockarquivo',
            name='tamanho_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djidockcomando',
            name='expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djidockcomando',
            name='mensagem_mqtt',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
