# Generated by Django 5.2.17 on 2026-09-02 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_dji_midias_fila'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DJIDRCSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('modo', models.CharField(choices=[('simulacao', 'Simulação'), ('real', 'Equipamento real')], default='simulacao', max_length=20)),
                ('status', models.CharField(choices=[('preparada', 'Preparada'), ('ativa', 'Ativa'), ('finalizada', 'Finalizada'), ('erro', 'Erro')], default='preparada', max_length=20)),
                ('altitude_maxima_m', models.PositiveSmallIntegerField(default=120)),
                ('distancia_maxima_m', models.PositiveIntegerField(default=500)),
                ('sequencia_atual', models.PositiveBigIntegerField(default=0)),
                ('ultimo_heartbeat_em', models.DateTimeField(blank=True, null=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_finalizacao', models.CharField(blank=True, max_length=255)),
                ('telemetria_simulada', models.JSONField(blank=True, default=dict)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('dock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_drc', to='core.djidock')),
                ('missao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_drc', to='core.djidockmissao')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_drc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='DJIDRCComando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.PositiveBigIntegerField()),
                ('roll', models.PositiveSmallIntegerField(default=1024)),
                ('pitch', models.PositiveSmallIntegerField(default=1024)),
                ('throttle', models.PositiveSmallIntegerField(default=1024)),
                ('yaw', models.PositiveSmallIntegerField(default=1024)),
                ('gimbal_pitch', models.PositiveSmallIntegerField(default=1024)),
                ('aceito', models.BooleanField(default=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='core.djidrcsessao')),
            ],
            options={
                'ordering': ['-sequencia'],
                'constraints': [models.UniqueConstraint(fields=('sessao', 'sequencia'), name='drc_sessao_sequencia_unica')],
            },
        ),
    ]
