# Generated by Django 5.2.17 on 2026-09-02 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_dji_cockpit_virtual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='djidrcsessao',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ativa')), fields=('dock',), name='drc_dock_sessao_ativa_unica'),
        ),
    ]
