# Generated by Django 5.2.17 on 2026-09-02 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_djidrcsessao_drc_dock_sessao_ativa_unica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DJIDockAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_operar', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concedido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_dock_concedidos', to=settings.AUTH_USER_MODEL)),
                ('dock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='core.djidock')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_dock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso à estação remota',
                'verbose_name_plural': 'Acessos às estações remotas',
                'ordering': ['dock__nome', 'usuario__username'],
                'constraints': [models.UniqueConstraint(fields=('dock', 'usuario'), name='dock_usuario_acesso_unico')],
            },
        ),
    ]
