# Generated by Django 5.2.17 on 2026-09-02 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_djidockacesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJIDockCanalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('aeronave', 'Aeronave'), ('dock', 'Estação remota')], max_length=20)),
                ('dispositivo_serial', models.CharField(max_length=100)),
                ('camera_indice', models.CharField(max_length=50)),
                ('video_indice', models.CharField(max_length=50)),
                ('video_id', models.CharField(max_length=255)),
                ('lente', models.CharField(blank=True, max_length=30)),
                ('lentes_alternativas', models.JSONField(blank=True, default=list)),
                ('disponivel', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais_video', to='core.djidock')),
            ],
            options={
                'verbose_name': 'Canal de vídeo da estação',
                'verbose_name_plural': 'Canais de vídeo das estações',
                'ordering': ['origem', 'camera_indice', 'video_indice'],
                'constraints': [models.UniqueConstraint(fields=('dock', 'video_id'), name='dock_video_id_unico')],
            },
        ),
    ]
