# Generated by Django 5.2.17 on 2026-09-02 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_djidockcanalvideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='djidockcanalvideo',
            name='qualidade',
            field=models.CharField(choices=[('adaptive', 'Adaptativa'), ('smooth', 'Fluida'), ('standard', 'Padrão'), ('high', 'Alta')], default='adaptive', max_length=20),
        ),
        migrations.AddField(
            model_name='djidockcanalvideo',
            name='solicitado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djidockcanalvideo',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streams_dock_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='djidockcanalvideo',
            name='status',
            field=models.CharField(choices=[('parado', 'Parado'), ('simulado', 'Ativo em simulação'), ('solicitado', 'Solicitado'), ('transmitindo', 'Transmitindo'), ('erro', 'Erro')], default='parado', max_length=20),
        ),
        migrations.AlterField(
            model_name='djidockcomando',
            name='tipo',
            field=models.CharField(choices=[('atualizar_estado', 'Atualizar estado'), ('reiniciar', 'Reiniciar Dock'), ('abrir_tampa', 'Abrir tampa'), ('fechar_tampa', 'Fechar tampa'), ('iniciar_missao', 'Iniciar missão'), ('pausar_missao', 'Pausar missão'), ('cancelar_missao', 'Cancelar missão'), ('iniciar_stream', 'Iniciar transmissão'), ('parar_stream', 'Parar transmissão'), ('trocar_lente', 'Trocar lente'), ('qualidade_stream', 'Alterar qualidade da transmissão')], max_length=30),
        ),
    ]
