# Generated by Django 5.2.17 on 2026-09-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_djidockcomando_autorizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djidockcomando',
            name='status',
            field=models.CharField(choices=[('bloqueado', 'Bloqueado'), ('pendente', 'Pendente'), ('processando', 'Em processamento'), ('enviado', 'Enviado'), ('confirmado', 'Confirmado'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], default='bloqueado', max_length=20),
        ),
    ]
