# Generated by Django 5.2.17 on 2026-09-03 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_djidockcomando_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='djidockcanalvideo',
            name='transmissao_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais_dock', to='core.transmissaoaovivo'),
        ),
    ]
