# Generated by Django 5.2.17 on 2026-09-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alertaseguranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosegurancausuario',
            name='ultimo_contador_mfa',
            field=models.BigIntegerField(default=-1),
        ),
    ]
