logLevel: info
logDestinations: [stdout]
authHTTPExclude:
  - action: api
  - action: metrics
rtsp: false
hls: false
rtmp: true
rtmpEncryption: strict
rtmpAddress: :1935
rtmpsAddress: :1936
rtmpServerCert: /certs/fullchain.pem
rtmpServerKey: /certs/privkey.pem
webrtc: true
webrtcAddress: :8889
webrtcEncryption: false
webrtcLocalUDPAddress: :8189
api: true
apiAddress: :9997
metrics: true
metricsAddress: :9998
paths:
  all_others:
