user sismod-consumer
topic read $SYS/broker/version
topic read sys/product/+/status
topic read thing/product/+/osd
topic read thing/product/+/state
topic read thing/product/+/events
topic read thing/product/+/services_reply

user sismod-publisher
topic write thing/product/+/services
topic write thing/product/+/drc/down
topic read thing/product/+/services_reply
