persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true

listener 1883 0.0.0.0
protocol mqtt
allow_anonymous false
password_file /mosquitto/data/passwords
acl_file /mosquitto/data/acl.conf
max_packet_size 10485760
max_inflight_messages 20
max_queued_messages 1000
